services:
  postgres:
    image: postgres:16
    container_name: quiz-postgres
    environment:
      POSTGRES_USER: quizUser
      POSTGRES_PASSWORD: quizPW
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - quiz-data:/var/lib/postgresql/data

volumes:
  quiz-data:

